openapi: 3.0.1
info:
  title: OBDX API
  description: OBDX API Documentation
  license:
    name: Apache 2.0
    url: 'https://springdoc.org'
  version: v0.0.1
externalDocs:
  description: OBDX Backend project repo
  url: 'https://github.com/txomin55/obdx-backend'
servers:
  - url: 'http://localhost:4000'
    description: Generated server url
paths:
  /api/masters/dogs:
    get:
      tags:
        - getDogs
      operationId: getDogs
      parameters:
        - in: header
          name: Authorization
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetDogListWeb'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/masters/dogs/{id}':
    get:
      tags:
        - getDog
      operationId: getDog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDogWeb'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Authorization header is missing!!
  headers:
    authorizationHeader:
      description: desc
      schema:
        type: string
  schemas:
    GetDogWeb:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
    GetDogListWeb:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          x-faker: name.firstName
        image:
          type: string
