openapi: 3.0.1
x-stoplight:
  id: irsv7m1yu2fwn
info:
  title: OBDX API
  description: OBDX API Documentation
  license:
    name: Apache 2.0
    url: 'https://springdoc.org'
  version: v0.0.1
externalDocs:
  description: OBDX Backend project repo
  url: 'https://github.com/txomin55/obdx-backend'
servers:
  - url: 'http://localhost:4000'
    description: Generated server url
paths:
  /api/masters/dogs:
    get:
      tags:
        - getDogs
      operationId: getDogs
      parameters:
        - in: header
          name: Authorization
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetDogListWeb'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/verify:
    get:
      tags:
        - verify
      operationId: verify
      parameters:
        - in: header
          name: Authorization
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /login:
    post:
      tags:
        - login
      operationId: login
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/masters/user:
    get:
      tags:
        - getUserData
      operationId: getUserData
      parameters:
        - in: header
          name: Authorization
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DogTrainerUserDetails'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  '/api/masters/dogs/{id}':
    get:
      tags:
        - getDog
      operationId: getDog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDogWeb'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /api/logout:
    get:
      tags:
        - logout
      operationId: logout
      parameters:
        - in: header
          name: Authorization
          description: JWT format bearer for Authorization header
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /loginUrl:
    get:
      tags:
        - loginUrl
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginUrlWeb'
      operationId: loginUrl
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Authorization header is missing!!
  headers:
    authorizationHeader:
      description: desc
      schema:
        type: string
  schemas:
    GetDogWeb:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        image:
          type: string
    DogTrainerUserDetails:
      type: object
      properties:
        owner:
          type: string
        organizations:
          type: array
          items:
            type: string
    GetDogListWeb:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          x-faker: name.firstName
        image:
          type: string
    LoginUrlWeb:
      title: LoginUrlWeb
      x-stoplight:
        id: 2oyw7r616bktz
      type: object
      properties:
        url:
          type: string
      required:
        - url
