name: Generate Java Stubs from OAS

on:
  push:
    paths:
      - openapi.yaml
  workflow_dispatch: {}

jobs:
  generate-java-stubs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      MAVEN_OPTS: -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
      ARCHETYPE_GROUP_ID: com.k9x
      ARCHETYPE_ARTIFACT_ID: oas-generator-archetype
      ARCHETYPE_VERSION: 1.0.0
      ARCHETYPE_PACKAGES_URL: https://maven.pkg.github.com/txomin55/k9x-oas-generator-archetype
      GITHUB_PACKAGES_URL: https://maven.pkg.github.com/txomin55/k9x-oas-definition
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
      MODULE_NAME: "OBDX OAS STUBS"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"
          cache-dependency-path: "${{ github.workspace }}/openapi.yaml"

      - name: Fetch archetype
        run: |
          mvn dependency:get \
            -Dartifact=$ARCHETYPE_GROUP_ID:$ARCHETYPE_ARTIFACT_ID:$ARCHETYPE_VERSION \
            -DremoteRepositories=github::::$ARCHETYPE_PACKAGES_URL \
            -s ci_settings.xml

      - name: Generate project
        working-directory: ${{ github.workspace }}
        run: |
          mvn archetype:generate -B \
            -DarchetypeGroupId=$ARCHETYPE_GROUP_ID \
            -DarchetypeArtifactId=$ARCHETYPE_ARTIFACT_ID \
            -DarchetypeVersion=$ARCHETYPE_VERSION \
            -DgroupId=com.obdx \
            -DartifactId=oas-definition-stubs \
            -Dname=$MODULE_NAME \
            -Dversion=0.0.1-SNAPSHOT \
            -DinteractiveMode=false \
            -DgithubRepo=${{ github.repository }} \
            -DoutputDirectory=${{ github.workspace }} \
            -s ci_settings.xml

      - name: Copy OpenAPI spec
        run: cp openapi.yaml ${{ github.workspace }}/oas-definition-stubs

      - name: Deploy
        run: mvn -f ${{ github.workspace }}/oas-definition-stubs/pom.xml clean deploy -s ${{ github.workspace }}/oas-definition-stubs/ci_settings.xml
