name: Generate Java Stubs from OAS

on:
  workflow_dispatch: {}

jobs:
  generate-java-stubs:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.12-eclipse-temurin-25-noble
    permissions:
      contents: read
      packages: write
    env:
      MAVEN_OPTS: -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
      ARCHETYPE_GROUP_ID: com.obdx.oas-generator-archetype
      ARCHETYPE_ARTIFACT_ID: oas-generator-archetype
      ARCHETYPE_VERSION: 1.0.0
      ARCHETYPE_PACKAGES_URL: https://maven.pkg.github.com/txomin55/obdx-oas-generator-archetype
      GITHUB_PACKAGES_URL: https://maven.pkg.github.com/txomin55/obdx-oas-definition
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: .m2/repository
          key: m2-${{ env.ARCHETYPE_VERSION }}
          restore-keys: |
            m2-

      - name: Fetch archetype
        run: |
          mvn dependency:get \
            -Dartifact=$ARCHETYPE_GROUP_ID:$ARCHETYPE_ARTIFACT_ID:$ARCHETYPE_VERSION \
            -DremoteRepositories=github::::$ARCHETYPE_PACKAGES_URL \
            -s ci_settings.xml

      - name: Update local archetype catalog
        run: |
          mvn -f ${{ github.workspace }}/.m2/repository/com/obdx/oas-generator-archetype/$ARCHETYPE_ARTIFACT_ID/$ARCHETYPE_VERSION/$ARCHETYPE_ARTIFACT_ID-$ARCHETYPE_VERSION.pom \
            archetype:update-local-catalog \
            -s ci_settings.xml

      - name: Generate project
        run: |
          mvn archetype:generate -B \
            -DarchetypeGroupId=$ARCHETYPE_GROUP_ID \
            -DarchetypeArtifactId=$ARCHETYPE_ARTIFACT_ID \
            -DarchetypeVersion=$ARCHETYPE_VERSION \
            -DgroupId=com.obdx.oas-stubs \
            -DartifactId=oas-stubs \
            -Dname=oas-stubs \
            -Dversion=0.0.1-SNAPSHOT \
            -DinteractiveMode=false \
            -DgithubRepo=${{ github.repository }} \
            -s ci_settings.xml

      - name: List generated files
        run: ls -la ${{ github.workspace }}

      - name: Copy OpenAPI spec
        run: cp openapi.yaml ${{ github.workspace }}/oas-stubs

      - name: Deploy
        run: mvn -f ${{ github.workspace }}/oas-stubs/pom.xml clean deploy -s ${{ github.workspace }}/oas-stubs/ci_settings.xml
