name: Generate Java Stubs from OAS

on:
  workflow_dispatch: {}

jobs:
  generate-java-stubs:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
      ARCHETYPE_GROUP_ID: com.obdx.oas-generator-archetype
      ARCHETYPE_ARTIFACT_ID: oas-generator-archetype
      ARCHETYPE_VERSION: 1.0.0
      ARCHETYPE_PACKAGES_URL: https://github.com/txomin55/obdx-oas-generator-archetype/packages
      GITHUB_PACKAGES_URL: https://github.com/txomin55/obdx-oas-definition/packages
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_ACTOR: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "maven"

      - name: Fetch archetype
        run: |
          mvn dependency:get \
            -Dartifact=$ARCHETYPE_GROUP_ID:$ARCHETYPE_ARTIFACT_ID:$ARCHETYPE_VERSION \
            -DremoteRepositories=github::::$ARCHETYPE_PACKAGES_URL \
            -s ci_settings.xml

      - name: Update local archetype catalog
        run: |
          mvn -f ${{ github.workspace }}/.m2/repository/com/obdx/oas-generator-archetype/$ARCHETYPE_ARTIFACT_ID/$ARCHETYPE_VERSION/$ARCHETYPE_ARTIFACT_ID-$ARCHETYPE_VERSION.pom \
            archetype:update-local-catalog \
            -s ci_settings.xml

      - name: Generate project
        run: |
          mvn archetype:generate -B \
            -DarchetypeGroupId=$ARCHETYPE_GROUP_ID \
            -DarchetypeArtifactId=$ARCHETYPE_ARTIFACT_ID \
            -DarchetypeVersion=$ARCHETYPE_VERSION \
            -DgroupId=com.obdx.oas-stubs \
            -DartifactId=oas-stubs \
            -Dname=oas-stubs \
            -Dversion=0.0.1-SNAPSHOT \
            -DinteractiveMode=false \
            -s ci_settings.xml

      - name: Copy OpenAPI spec
        run: cp openapi.yaml ${{ github.workspace }}/dog-trainer-pack

      - name: Deploy
        run: mvn -f ${{ github.workspace }}/dog-trainer-pack/pom.xml clean deploy -s ${{ github.workspace }}/dog-trainer-pack/ci_settings.xml
